import {
  Facebook,
  Handshake,
  Headset,
  Instagram,
  Lightbulb,
  Linkedin,
  Star,
  ThumbsUp,
  TimerReset,
} from "lucide-react";

export const navLinks = [
  {
    label: "About us",
    href: "/about-us",
  },
  {
    label: "Packages",
    href: "/#pricing",
  },
  {
    label: "Services",
    href: "/#services",
  },
  {
    label: "Contact us",
    href: "/contact-us",
  },
] as const;

export const whyChooseUsData = [
  {
    id: 1,
    Icon: Star,
    title: "Proven Track Record",
    description:
      "With a track record of delivering measurable results and exceeding client expectations, we're the trusted choice for businesses seeking success in today's competitive landscape.",
  },
  {
    id: 2,
    Icon: ThumbsUp,
    title: "Expertise Across Industries",
    description:
      "Our team of seasoned professionals brings expertise across various industries, ensuring that we understand the unique challenges and opportunities specific to your business niche.",
  },
  {
    id: 3,
    Icon: TimerReset,
    title: "Customized Solutions",
    description:
      "We believe in personalized approaches tailored to each client's needs. Our customized solutions are designed to address your specific goals and drive sustainable growth.",
  },
  {
    id: 4,
    Icon: Headset,
    title: "Innovative Strategies",
    description:
      "Stay ahead of the curve with our innovative strategies. We continuously adapt to the ever-changing digital landscape, leveraging the latest tools and techniques to maximize your success.",
  },
  {
    id: 5,
    Icon: Lightbulb,
    title: "Value for Money",
    description:
      "We offer cost-effective solutions without compromising on quality. Get the most out of your investment with our competitive pricing and exceptional service.",
  },
  {
    id: 6,
    Icon: Handshake,
    title: "Dedicated Support",
    description:
      "Your success is our priority. Count on us for dedicated support and ongoing assistance, ensuring that you have the resources and guidance you need to thrive in today's dynamic business environment.",
  },
] as const;

export const socialLinks = [
  {
    platform: "Facebook",
    link: "facebook.com",
    Icon: Facebook,
  },
  {
    platform: "Instagram",
    link: "instagram.com",
    Icon: Instagram,
  },
  {
    platform: "LinkedIn",
    link: "linkedin.com",
    Icon: Linkedin,
  },
] as const;

export const employees = [
  {
    name: "Mohammed Nazmul Hossain",
    position: "Chief Operating Officer,",
    image: "https://i.ibb.co/JRKHjhf/Nazmul.png",
  },
  {
    name: "Robin M. Rahman",
    position: " Chief Executive Officer",
    image: "https://i.ibb.co/88mzwLt/Robin.png",
  },
  {
    name: "Syed Hameem Bin Arshad",
    position: "Chief Business Officer",
    image: "https://i.ibb.co/9wQ1MTp/Hameem.png",
  },
] as const;

export const termsOfServices = [
  {
    term: "Eligibility",
    description:
      "Our services are accessible only to those who are at least 18 years of age. Byengaging with our services, you confirm that you meet this age requirement.",
  },
  {
    term: "Services",
    description:
      "thrivenvision offers a broad spectrum of digital services to a global clientele. In using our services, you commit to providing truthful and comprehensive details about your pro ect requirements and agree to supply all necessary materials for the successful completion of your project.",
  },
  {
    term: "Payment",
    description:
      "Access to our services incurs a charge, the details of which will be provided in our service quote. We require full payment in advance of project initiation",
  },
  {
    term: "Copyright",
    description:
      "You guarantee that you hold or possess the requisite licenses, rights, and permissions for any material you provide for your project. You agree that the output generated by us becomes your property upon full settlement of payment",
  },
  {
    term: "Confidentiality",
    description:
      "thrivenvision commits to maintaining the confidentiality of all materials and information you provide and will not disclose such information to any third parties without your explicit consent.",
  },
  {
    term: "Revision and Approval",
    description:
      "We offer a reasonable number of revisions to ensure the final product aligns with your specifications. Final approval of the project by you will signify the project's completion, and any subsequent modifications may incur additional fees.",
  },
  {
    term: "Liability",
    description:
      "thrivenvision shall not be liable for any direct or indirect damages, including but not limited to loss of profits, savings, or incidental or consequential damages, that may result from utilizing our services.",
  },
  {
    term: "Termination",
    description:
      "We reserve the right to terminate our services at any discretion should we ascertain non-compliance with our terms and conditions on your part",
  },
  {
    term: "Modification",
    description:
      "thrivenvision reserves the right to alter these terms and conditions at any moment, without prior notification. By continuing to use our services, you consent to be bound by such modifications..",
  },
] as const;
